#!/bin/bash
#
# Copyright (C) 2013 Insignal
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

source $(dirname ${0})/adb-include.sh

ADB_REPEAT=1

function sub_checkoptions() {
	local GETOPTS
	local OPTIND
	local OPT
	local OPTARG

	#GETOPTS="a:b:c:d:e:f:g:h:i:j:k:l:m:n:o:p:q:r:s:t:u:v:w:x:y:z:"
	GETOPTS="abcdefghijklmnopqrstuvwxyz"

	while getopts "$GETOPTS" OPT
	do
		case ${OPT} in
			c)	DMSGOPT="-c"
				;;
			l)	DMSGLOOP="on"
				;;
		esac
	done
}

function adb_handler() {
	sub_checkoptions $@

	if [ -z "$DMSGLOOP" ]; then
		adb ${ADBOPT} shell dmesg $DMSGOPT
		return $?
	else
		adb ${ADBOPT} shell "
while :
do
dmesg -c
ret=\$?
[ \$ret -ne 0 ] && exit 1
sleep 1
done
exit \$ret
"
		return $?
	fi

}

adb_main $@

