#!/bin/bash
#
# Copyright (C) 2013 Insignal
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

CL_WHT="\033[1m"
CL_RED="\033[31m"
CL_GRN="\033[32m"
CL_YLW="\033[33m"
CL_BLU="\033[34m"
CL_MAG="\033[35m"
CL_CYN="\033[36m"
CL_RST="\033[0m"

TOOLCHAIN_BASE=(
"/home/mm/02_Compiler"
)

function _cc_setup() {
echo "Setup for ARM cross-compiler."
CNT=1
for BASE in "${TOOLCHAIN_BASE[@]}"
do
	for SUBBASE in ${BASE}/{bin,*/bin,}
	do
		[ ! -e "${SUBBASE}" ] && continue;
		RESULTS=( $(find ${SUBBASE} -maxdepth 1 -name "*-gcc") )
		[ -z "${RESULTS}" ] && continue;
		for RESULT in "${RESULTS[@]}"
		do
			echo -e ${CNT}"." \
				${CL_WHT} \
				$(${RESULT} --version | grep arm.*gcc) \
				$(${RESULT} --version | grep aarch64.*gcc) \
				${CL_RST} \
				${RESULT/-gcc/-}
		
			SEARCH_LIST[$CNT]="${RESULT}"
			let "CNT=${CNT}+1"
		done
	done
done

echo ""
read -p "Select toolchain: " SELECTED
SELECT=$(echo ${SELECTED} | sed -e 's/[^0-9]*//g')
[ -z "${SELECTED}" ] && return;
[ ${SELECTED} -eq 0 ] && return;
[ ${SELECTED} -gt ${CNT} ] && return;

CC_FULL="${SEARCH_LIST[${SELECTED}]}"
CC_PATH=$(dirname "${CC_FULL}")
CC_FILE=$(basename "${CC_FULL}")

CC_CHECK="$(which ${CC_FILE})"
if [ -z "${CC_CHECK}" ] || [ "${CC_CHECK}" != "${CC_FULL}" ]; then
	export PATH=${CC_PATH}:${PATH}
fi

export "ARCH=arm"
echo "ARCH=${ARCH}"
export "CROSS_COMPILE_PATH=${CC_PATH}"
echo "CROSS_COMPILE_PATH=${CC_PATH}"
export "CROSS_COMPILE=${CC_FILE/-gcc/-}"
echo "CROSS_COMPILE=${CROSS_COMPILE}"
}

_cc_setup
