#!/bin/bash
#
# Copyright (C) 2013 Insignal
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

CL_RED="\033[31m"
CL_GRN="\033[32m"
CL_YLW="\033[33m"
CL_BLU="\033[34m"
CL_MAG="\033[35m"
CL_CYN="\033[36m"
CL_RST="\033[0m"

CC_PKG="arm-eabi"
CC_VER="4.6"

[ ! -z "$1" ] && CC_PKG="$1"
[ ! -z "$2" ] && CC_VER="$2"

CC_IDX=$(echo | bash cc-setup | grep "${CC_PKG}" | grep "${CC_VER}" | sed -e 's/\..*//')

for env in $(echo ${CC_IDX} | bash cc-setup | grep '=')
do
	export ${env}
	echo ${env}
done

CC_FULL="${CROSS_COMPILE_PATH}/${CROSS_COMPILE}gcc"
CC_CHECK="$(which ${CROSS_COMPILE}gcc)"
if [ -z "${CC_CHECK}" ] || [ "${CC_CHECK}" != "${CC_FULL}" ]; then
	export PATH=${CROSS_COMPILE_PATH}:${PATH}
fi

echo "CROSS_COMPILE_VERSION="$(${CROSS_COMPILE}gcc --version | grep arm.*gcc)

