#!/bin/bash
#
# Copyright (C) 2013 Insignal
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

CL_WHT="\033[1m"
CL_RED="\033[31m"
CL_GRN="\033[32m"
CL_YLW="\033[33m"
CL_BLU="\033[34m"
CL_MAG="\033[35m"
CL_CYN="\033[36m"
CL_RST="\033[0m"

function print_usage()
{
echo "find keyword from files.
USAGE: gref <pattern> [file or path] ..."
exit 1
}

if [ $# -eq 0 ]; then
    print_usage
fi

keyword=$1
shift 1

dircnt=0
optcnt=0
for arg in "$@"
do
	if [ -d "${arg}" ] || [ -L "${arg}" ]; then
		dirs[$dircnt]="${arg}"
		let "dircnt=${dircnt}+1"
	else
		opts[$optcnt]="-name '${arg}' -o"
		let "optcnt=${optcnt}+1"
	fi
done

[ ${dircnt} -ne 0 ] && for d in "${dirs[@]}"; do dir="\"${d}\" ${dir}"; done
[ ${optcnt} -eq 1 ] && opt="${opts[@]}" && opt=${opt/-o}" -print0"
[ ${optcnt} -gt 1 ] && opt="\( ${opts[@]} \)" && opt=${opt/-o \\\)/\\\)}" -print0"

[ -z "$dir" ] && dir="."
[ -z "$opt" ] && opt="-print0"

echo -e ${CL_WHT}"================================================================================"${CL_RST}

eval "find ${dir} \
	-name '.repo' -prune -o \
	-name '.git' -prune -o \
	-name '.svn' -prune -o \
	-name 'out' -prune -o \
	-name 'tags' -prune -o \
	-name 'Debug' -prune -o \
	-name '*.o' -prune -o \
	-name '*.o.*' -prune -o \
	-name '*.a' -prune -o \
	-name '*.ko*' -prune -o \
	-name '*.so*' -prune -o \
	-name '*.cmd' -prune -o \
	-name '*.mod.c' -prune -o \
	-name '*.js' -prune -o \
	-name '*.tmp' -prune -o \
	-type f ${opt} \
	| xargs -0 grep --color -n '$keyword' ."

echo -e ${CL_WHT}"================================================================================"${CL_RST}

