#!/bin/bash
#
# Copyright (C) 2013 Insignal
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

CL_RED="\033[31m"
CL_GRN="\033[32m"
CL_YLW="\033[33m"
CL_BLU="\033[34m"
CL_MAG="\033[35m"
CL_CYN="\033[36m"
CL_RST="\033[0m"

CL_LINE=${CL_YLW}"================================================================================"${CL_RST}

CPU_COUNT=$(grep processor /proc/cpuinfo | wc -l)

echo -e ${CL_LINE}
echo "HOSTCC_VERSION="$(gcc --version | grep gcc)
[ -f envsetup.sh ] && source envsetup.sh
[ -f envsetup ] && source envsetup

echo -e ${CL_LINE}
time make -j${CPU_COUNT} $@
RET=$?
[ ${RET} -ne 0 ] && echo "" && echo -e ${CL_RED}"Error occured !!!!!"${CL_RST}
echo -e ${CL_LINE}

exit ${RET}

