#!/bin/bash
#
# Copyright (C) 2013 Insignal
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

TARGETPATH=/mnt/mtp

if [ -d "${TARGETPATH}" ]; then
	sudo umount "${TARGETPATH}"
else
	mkdir -p "${TARGETPATH}"
fi

sudo mtpfs -o allow_other "${TARGETPATH}"
[ $? -ne 0 ] && echo "error on mptfs" && exit 1

nautilus "${TARGETPATH}"
[ $? -ne 0 ] && echo "error on nautilus" && exit 1

#sudo umount "${TARGETPATH}"
