#!/bin/bash
#
# Copyright (C) 2013 Insignal
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

[ $# -eq 0 ] && \
echo "Usage:
$0 <tag1> [tag2]
print oneline log from tag1 to tag2 or HEAD" && \
exit 0

export TAG1="$1"
export TAG2="$2"
repo forall -c '
[ ! -z "$(git tag | grep $TAG1)" ] && \
[ ! -z "$(git log --oneline $TAG1..$TAG2)" ] && \
echo $REPO_PROJECT && \
git log --oneline $TAG1..$TAG2 && \
echo;
'
